#!/usr/bin/env bash

# Prints the Homebrew formula for a release. Every line of it follows from the
# version and the four checksums, so it is generated whole rather than patched:
# no regex has to keep matching a file in another repo. Reads the .sha256 files
# the release build produced.

set -euo pipefail

version="${1:?usage: render-formula.sh <version> <dist dir>}"
dist="${2:?usage: render-formula.sh <version> <dist dir>}"
url_base="https://github.com/hernancerm/git-timeline/releases/download/${version}"

assets='git-timeline-macos-arm64
        git-timeline-linux-arm64 git-timeline-linux-x86_64'

for asset in ${assets}
do
  if [[ ! -f "${dist}/${asset}.tar.gz.sha256" ]]
  then
    echo "error: missing ${dist}/${asset}.tar.gz.sha256" >&2
    exit 1
  fi
done

sha() {
  awk '{ print $1; exit }' "${dist}/${1}.tar.gz.sha256"
}

cat <<EOF
# Generated by .github/scripts/render-formula.sh in hernancerm/git-timeline.
# Edit that script, not this file: the release workflow overwrites it.
class GitTimeline < Formula
  desc "Git log wrapper improving readability"
  homepage "https://github.com/hernancerm/git-timeline"
  version "${version}"

  on_macos do
    # GraalVM 25 has no macOS Intel build, so neither do we. Without this an
    # Intel Mac would fail on a missing url instead of saying why.
    depends_on arch: :arm64

    on_arm do
      url "${url_base}/git-timeline-macos-arm64.tar.gz"
      sha256 "$(sha git-timeline-macos-arm64)"
    end
  end

  on_linux do
    on_arm do
      url "${url_base}/git-timeline-linux-arm64.tar.gz"
      sha256 "$(sha git-timeline-linux-arm64)"
    end

    on_intel do
      url "${url_base}/git-timeline-linux-x86_64.tar.gz"
      sha256 "$(sha git-timeline-linux-x86_64)"
    end
  end

  def install
    bin.install "git-timeline"
    # Both are '#compdef -', so each only defines its own function. Whichever
    # _git the user has picks up the name it looks for; the other sits unused.
    zsh_completion.install "completions/_git_timeline", "completions/_git-timeline"
  end

  test do
    system "git-timeline", "--version"
  end
end
EOF
