## Generate the _git_timeline (or _git-timeline) Zsh completion file.
##
## Usage: zsh _git_timeline.generate.zsh > _git_timeline   # upstream _git (Homebrew, etc.)
##        zsh _git_timeline.generate.zsh > _git-timeline   # native Zsh _git (Ubuntu/Debian, etc.)
##
## Outputs the generated completion function to stdout.
## The caller is responsible for placing the file in a directory on $fpath.
##
## How 'git timeline --<Tab>' works:
##
## There are two _git Zsh completion implementations in the wild:
##
##   A) Upstream (bash-bridge) — shipped by Homebrew and other package managers
##      that follow git's own contrib/completion. It looks up _git_timeline()
##      (underscore) in $functions and calls it. _git_timeline() sources
##      git-completion.bash and delegates to _git_log, giving identical
##      completions to 'git log'.
##
##   B) Native Zsh — shipped by Ubuntu/Debian and other distros as a standalone
##      pure-Zsh implementation. It looks up _git-timeline() (hyphen) in
##      $functions and calls it. _git-timeline() delegates directly to
##      _git-log (no bash bridge needed).
##
## This script detects which implementation is active by searching $fpath for
## the _git file and inspecting it, then generates the appropriate output.
##
## Troubleshooting:
##
## If 'git timeline --<TAB>' completions do not work, the issue is usually that
## git-completion.bash is not in the same directory as _git. Add a zstyle to
## ~/.zshrc pointing to the correct path for your git installation:
##
##   Homebrew (macOS):
##     zstyle ':completion:*:*:git:*' script \
##       $(brew --prefix)/share/zsh/site-functions/git-completion.bash
##     Running 'brew reinstall git' often fixes this — check its Caveats output
##     for the completions directory.
##
##   System Git (Ubuntu/Debian/Fedora/Arch):
##     zstyle ':completion:*:*:git:*' script \
##       /usr/share/bash-completion/completions/git

setopt ERR_EXIT

# 1. DETECT GIT VERSION
# ---

if (( ! $+commands[git] )); then
    echo "ERROR: git is not installed or not in PATH" >&2
    exit 1
fi

# Strip OS-specific suffixes (e.g. "(Apple Git-130)" on macOS)
git_version=$(git --version | sed 's/^git version //' | awk '{print $1}')
if [[ -z "$git_version" ]]; then
    echo "ERROR: Could not parse git version from 'git --version'" >&2
    exit 1
fi

# 2. DETECT _git IMPLEMENTATION
# ---
# Search $fpath for the active _git completion file and inspect it to determine
# whether it is the upstream bash-bridge implementation (defines _git_log) or
# the native Zsh implementation (defines _git-log).

local git_zsh_completion=""
for dir in $fpath; do
    if [[ -f "$dir/_git" ]]; then
        git_zsh_completion="$dir/_git"
        break
    fi
done
if [[ -z "$git_zsh_completion" ]]; then
    echo "ERROR: _git Zsh completion file not found in \$fpath" >&2
    exit 1
fi

local git_impl=""
if grep -q '^__git_complete_command ()' "$git_zsh_completion"; then
    git_impl="upstream"
elif grep -q '^_git-log ()' "$git_zsh_completion"; then
    git_impl="native"
else
    echo "ERROR: Could not determine _git implementation from $git_zsh_completion" >&2
    echo "  Neither '__git_complete_command ()' nor '_git-log ()' found." >&2
    exit 1
fi

# 3. GENERATE completion function (stdout)
# ---

if [[ "$git_impl" == "native" ]]; then
    # Native Zsh _git (Ubuntu/Debian and similar): delegates with hyphens.
    # _git-timeline() just calls _git-log() directly — no bash bridge needed.
    cat << 'NATIVE'
#compdef -

# Generated by _git_timeline.generate.zsh
# See: https://github.com/hernancerm/git-timeline/tree/main/completions
#
# '#compdef -' causes compinit to register this file as an autoloadable
# function stub without binding it to any command. After 'exec zsh', the
# native _git completion finds _git-timeline() in $functions and calls it
# when completing 'git timeline --<TAB>'.

_git-timeline () {
  _git-log
}

_git-timeline
NATIVE
    exit 0
fi

# Upstream bash-bridge _git (Homebrew and similar): delegates with underscores.
# _git_timeline() sources git-completion.bash and delegates to _git_log.

# 4. LOCATE git-completion.bash
# ---
# Determine the installation from the git executable path. For Homebrew, check
# the known Homebrew location. For all other git installs, probe a list of
# generic candidate locations. First match wins.

git_path=$(which git)
local git_completion_bash_filepath=""
local candidates=()

if (( $+commands[brew] )) && [[ "$git_path" == "$(brew --prefix)/bin/git" ]]; then
    candidates=(
        "$(brew --prefix)/share/zsh/site-functions/git-completion.bash"
    )
else
    candidates=(
        "/usr/share/bash-completion/completions/git"                       # Ubuntu/Debian/Fedora/Arch (apt, dnf, pacman)
        "/usr/local/share/bash-completion/completions/git"                 # Manual install (prefix=/usr/local)
        "/usr/local/share/bash-completion/completions/git-completion.bash" # Manual install (alternate name)
    )
fi

for candidate in "${candidates[@]}"; do
    if [[ -f "$candidate" ]]; then
        git_completion_bash_filepath="$candidate"
        break
    fi
done
if [[ -z "$git_completion_bash_filepath" ]]; then
    echo "ERROR: git-completion.bash not found. Searched:" >&2
    for candidate in "${candidates[@]}"; do
        echo "  $candidate" >&2
    done
    exit 1
fi

# 5. DOWNLOAD git-completion.zsh (temporary, for awk extraction only)
# ---
# git-completion.zsh is not installed locally by any standard git package.
# We download it temporarily to extract the __gitcomp* wrapper functions via
# awk. The file is cleaned up on exit and never installed anywhere.

base_url="https://raw.githubusercontent.com/git/git/v${git_version}/contrib/completion"
zsh_url="${base_url}/git-completion.zsh"

temp_dir=$(mktemp -d)
trap "rm -rf $temp_dir" EXIT

if ! curl -fsSL "$zsh_url" -o "$temp_dir/git-completion.zsh" 2>/dev/null; then
    echo "ERROR: Failed to download git-completion.zsh" >&2
    echo "  URL: $zsh_url" >&2
    exit 1
fi

# 6. GENERATE _git_timeline (stdout) — upstream bash-bridge path
# ---
# '#compdef -' tells compinit to autoload this file as a function stub without
# binding it to any command. This makes _git_timeline() available in $functions
# from shell init, so the _git bridge's __git_complete_command() can find and
# call it when completing 'git timeline --<TAB>'.
#
# The function uses git's zsh-to-bash bridge pattern from git-completion.zsh:
#   1. Source git-completion.bash (GIT_SOURCING_ZSH_COMPLETION=y suppresses
#      bash 'complete' registrations that are no-ops in zsh)
#   2. Define zsh wrapper functions (__gitcomp* etc.) copied verbatim from
#      git-completion.zsh — these translate bash completion output to zsh compadd
#   3. Set up bash-style cursor variables (cur/cword/prev) from zsh's 1-indexed
#      CURRENT/words[] before ksh emulation switches arrays to 0-indexed
#   4. Call _git_log via 'emulate ksh -c' for bash/ksh compatibility

cat << HEADER
#compdef -

# Generated by _git_timeline.generate.zsh
# See: https://github.com/hernancerm/git-timeline/tree/main/completions
#
# Git version: ${git_version}
#
# '#compdef -' causes compinit to register this file as an autoloadable
# function stub without binding it to any command. After 'exec zsh', the
# _git completion bridge finds _git_timeline() in \$functions and calls it
# when completing 'git timeline --<TAB>'.

# STEP 1: Source git-completion.bash
# ---
# Path evaluated at completion time. GIT_SOURCING_ZSH_COMPLETION=y tells
# git-completion.bash it is running in a zsh context; 'complete' is
# neutralised so bash registration calls are no-ops.

local script="${git_completion_bash_filepath}"
if [[ ! -f "\$script" ]]; then
    _message "git-completion.bash not found at \$script"
    return 1
fi
local old_complete="\$functions[complete]"
functions[complete]=:
GIT_SOURCING_ZSH_COMPLETION=y . "\$script"
functions[complete]="\$old_complete"

# STEP 2: Zsh-compatible wrappers for bash completion primitives
# ---
# Copied verbatim from git-completion.zsh v${git_version} (official git source).
# These translate bash COMPREPLY / __gitcomp calls into zsh compadd calls.

HEADER

# Append __gitcomp* wrappers: everything from __gitcomp() up to _git_zsh()
awk '
    /^__gitcomp \(\)/  { printing=1 }
    /^_git_zsh \(\)/   { exit }
    printing           { print }
' "$temp_dir/git-completion.zsh"

# Validate that the expected wrapper functions were actually extracted.
# If git ever renames or restructures these, fail loudly rather than silently
# producing a broken completion file.
for fn in __gitcomp __gitcomp_direct __gitcomp_nl __gitcomp_file; do
    if ! awk "/^${fn} \(\)/{found=1} END{exit !found}" "$temp_dir/git-completion.zsh"; then
        echo "ERROR: Failed to extract ${fn}() from git-completion.zsh v${git_version}" >&2
        echo "  The structure of git-completion.zsh may have changed in this version." >&2
        echo "  Please file an issue at https://github.com/hernancerm/git-timeline" >&2
        exit 1
    fi
done

cat << 'FOOTER'

# STEP 3: Entry point
# ---
# Set up bash-style cursor variables while still in zsh context (1-indexed
# arrays). CURRENT is a zsh 1-based index; words[CURRENT] is the word under
# the cursor. These must be captured before ksh emulation switches arrays to
# 0-indexed — otherwise words[CURRENT] is out of bounds and cur="".
#
# Then call _git_log via 'emulate ksh -c' (not 'emulate -L ksh' at function
# top) so the locals set above remain visible inside _git_log.

local cur cword prev
local __git_repo_path
local __git_cmd_idx=1

cur=${words[CURRENT]}
prev=${words[CURRENT-1]}
let cword=CURRENT-1

emulate ksh -c _git_log
FOOTER
