name: Build binaries
on:
  workflow_dispatch:

jobs:

  macos-x86:
    name: macos-x86
    runs-on: macos-13
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repo
        uses: actions/checkout@v5

      - name: Build binary
        run: |
          # Install SDKMAN!
          curl -s "https://get.sdkman.io" | bash
          source "${HOME}/.sdkman/bin/sdkman-init.sh"

          # Install Java 21 Graal
          sdk install java 21.0.8-graal
          export JAVA_HOME="${HOME}/.sdkman/candidates/java/current"
          export GRAALVM_HOME="${JAVA_HOME}"
          java --version

          # Build binary
          make bin

          # Package binary
          cp -v target/git-timeline .
          tar czf git-timeline-macos-x86.tar.gz git-timeline
